keys:
  - &crusader age1grdprksjjlycrcfy9snkmg7nc9spxg7l4676azd2nt972zgyselsdp688l
  - &guide age13gjyu480526r7v4flwk9ys7e9xdrq7aut6f5n0cr8uem89kgcv7svpvzc4
  - &guide2 age1dgpkyw8p86m2uzak34m99sp46n2khsdt5n0ssuhrm748g9t97e0sn7qxtu
  - &sentinel age1xj96tal5tkqz0axjf7vzj925ud5j547mtku796xgks4g825x8yts7zln96
creation_rules:
  - path_regex: secrets/guide-private.yaml$
    key_groups:
    - age:
      - *crusader
      - *guide
  - path_regex: secrets/guide-public.yaml$
    key_groups:
    - age:
      - *crusader
      - *guide
  - path_regex: secrets/guide2-private.yaml$
    key_groups:
    - age:
      - *crusader
      - *guide2
  - path_regex: secrets/guide2-public.yaml$
    key_groups:
    - age:
      - *crusader
      - *sentinel
      - *guide2
  - path_regex: secrets/sentinel-private.yaml$
    key_groups:
    - age:
      - *crusader
      - *sentinel
  - path_regex: secrets/sentinel-public.yaml$
    key_groups:
    - age:
      - *crusader
      - *sentinel
      - *guide2
